### ISSUE TITLE
Product Checklist

### ISSUE THREAD

**Issue by alejandro-lunag** [daniel-enqz/akord#61]
- [x] Your app is up
- [x] Favicon 
- [x] Naked domain is redirected to www
- [x] Title tag is set
- [x] Open Graph meta tags are properly set
- [x] 404 and 500 pages are customized
- [x] og:image has the right dimensions
